name: Monthly Sync

on:
  schedule:
    - cron: '0 0 1 * *' # runs at midnight on the first day of every month

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync Functions
      run: npx ts-node scripts/sync-functions

    - name: Sync Events
      run: npx ts-node scripts/sync-events
